M48
; DRILL file {KiCad (6.0.0)} date Wed Jan 12 17:49:14 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-12T17:49:14+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X92.019Y-109.906
X93.04Y-96.67
X106.74Y-96.67
T0
M30
